services:
  mongo:
    image: mongo:8
    container_name: mongo_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./back-end
    container_name: blog_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./back-end/.env
    depends_on:
      - mongo

  frontend:
    build:
      context: ./front-end
    container_name: blog_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data: